### PR TITLE
fix configuration file path to a more rational one

### LINKED ISSUE #5: i don't like the default config file location and default name
`/usr/local/etc/config.json`  is supposed to changed to a better location and better name, for less confusion.

### PR DESCRIPTION
**Pull request by timqi**
fix #5

### CODE REVIEW

**Comment by timqi** [comment]
seems no response when parse download url in checker.sh of travis-ci @Doublemine

**Comment by Doublemine** [comment]
@timqi Thanks for PR, #5 point to  the conf file location can be confusion. I think migrate conf file to new dir may be better choice. Such as `/usr/local/etc/v2ray/config.json`.  And what's your suggestions?

**Comment by Doublemine** [comment]
Pls update `readme.md` as well, Thx.

**Comment by Doublemine** [comment]
@timqi When i test this pr, it will cause the error: `Error: No such file or directory - v2ray/config.json`. And i guess below code may cause some error: 

```ruby
etc.install "v2ray/config.json"
```

Had you tested it ?

**Comment by timqi** [comment]
Sorry for that I don't know how does `etc.install` work. It may cuz v2ray directory in etc path doesn't created before. Please help handling this at your ease.

**Comment by Doublemine** [comment]
Maybe i guess you can try this:

```ruby
def install
    bin.install "v2ray"
    bin.install "v2ctl"
    bin.install "geoip.dat"
    bin.install "geosite.dat"
    (etc/"v2ray").mkpath
    etc.install "config.json" => "v2ray/config.json"
 end
```
And do some improve, i have not verified whether it is work, so you should test it on your mac env.

**Review by Doublemine — APPROVED** [review]

**Pull request merged**
